### ISSUE TITLE
unable to login to application after upgrading to IS 5.11 with <EnableEmailUserName>true</EnableEmailUserName>

### ISSUE THREAD

**Issue by hari819** [wso2/product-is#10760]
Hello wso2 team,

@madurangasiriwardena 
@JKAUSHALYA 
@thushaaanthan 
@pulasthi7 
 @godwinamila 
@omindu 
@thanujalk 
@isharac 
@tharindu-bandara 

We were using IS 5.10 , because of below error during logout  
`ERROR {org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[bridgeservlet]} - Servlet.service() for servlet [bridgeservlet] in context with path [/] threw exception org.wso2.carbon.identity.base.IdentityRuntimeException: Invalid tenant domain `  , based on the suggestion from https://stackoverflow.com/questions/46771416/wso2-is-invalid-tenant-domain-when-providing-id-token-hint-to-logout-endpoint, we have enabled the below property in carbon.xml 

`<EnableEmailUserName>true</EnableEmailUserName>`  , even without this property email user name was working but throwing the above error . we were using usernames with email as well as without email in 5.10 version which is not working in the new 5.11 version.

With the same configuration in 5.11 version of IS , we are unable to login to the application with the below error ,
"invalid username!, username should be an email address"
![image](https://user-images.githubusercontent.com/12997071/102046648-b8b9b600-3e01-11eb-9b54-ec3f7c9f6af9.png)

for users logging in using the username without email.

could you please let me know what is that we need to change to make both usernames with and without email working as previous version of IS,
 
i have tried adding an email domain to the admin user like admin@123.com , but even with this username ,i am unable to login even to IS console as well as my application ,

**How to reproduce:**
Enable property `<EnableEmailUserName>true</EnableEmailUserName>` in 5.11 and try to login with username and not the email username, 

**Expected behavior:**
User should be able to login with username as well as email username,

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: IS 5.11
 - OS: [e.g., Windows, Linux, Mac]
 - Database:Oracle
 - Userstore: JDBC

---

### Optional Fields

**Related issues:**
https://docs.wso2.com/display/IS570/Using+Email+Address+as+the+Username
https://docs.wso2.com/display/ADMIN44x/Working+with+Properties+of+User+Stores
https://github.com/wso2/product-is/issues/6728
https://github.com/wso2/product-is/issues/7485

**Suggested labels:**

**Comment by senthalan** [comment]
Seems like you are referring to old documentation. 

Here is the lastest documentation email as username in 5.11.0. https://is.docs.wso2.com/en/latest/learn/using-email-address-as-the-username/#using-email-address-as-the-username


From 5.9.0 onwards we have moved all the configuration to [new configuration model](https://is.docs.wso2.com/en/5.9.0/references/new-configuration-model/). So going forward better to follow the corresponding version documentation.

**Comment by hari819** [comment]
> Seems like you are referring to old documentation.
> 
> Here is the lastest documentation email as username in 5.11.0. https://is.docs.wso2.com/en/latest/learn/using-email-address-as-the-username/#using-email-address-as-the-username
> 
> From 5.9.0 onwards we have moved all the configuration to [new configuration model](https://is.docs.wso2.com/en/5.9.0/references/new-configuration-model/). So going forward better to follow the corresponding version documentation.

thanks @senthalan  , i saw the link during migration from 5.7 to 5.9 and did not switch to deployment,toml configuration , instead i deleted and continued the existing configuration in carbon.xml , identity.xml   based on ,  
![image](https://user-images.githubusercontent.com/12997071/102052040-8f9e2300-3e0b-11eb-93d2-55367fae6d58.png)

now is it mandatory to move to the new configuration model ? ,  it was all working in 5.9 and 5.10 version .

thanks,
Hari

**Comment by hari819** [comment]
> > Seems like you are referring to old documentation.
> > Here is the lastest documentation email as username in 5.11.0. https://is.docs.wso2.com/en/latest/learn/using-email-address-as-the-username/#using-email-address-as-the-username
> > From 5.9.0 onwards we have moved all the configuration to [new configuration model](https://is.docs.wso2.com/en/5.9.0/references/new-configuration-model/). So going forward better to follow the corresponding version documentation.
> 
> thanks @senthalan , i saw the link during migration from 5.7 to 5.9 and did not switch to deployment,toml configuration , instead i deleted and continued the existing configuration in carbon.xml , identity.xml based on ,
> ![image](https://user-images.githubusercontent.com/12997071/102052040-8f9e2300-3e0b-11eb-93d2-55367fae6d58.png)
> 
> now is it mandatory to move to the new configuration model ? , it was all working in 5.9 and 5.10 version .
> 
> thanks,
> Hari

also we would like to have support for username with and without an email domain, @senthalan  could you please point me to some documentation to achieve this ,

Thanks,
Hari

**Comment by hari819** [comment]
@senthalan ,  with this property enabled  `<EnableEmailUserName>true</EnableEmailUserName>`
both username with and without email domain does not work for me ,

wso2 console also has error during login with admin@123.com as username mentioned in `user-mgmt.xml` as below ,

          ```
  <AdminUser>
                <UserName>admin@123.com</UserName>
                <Password>admin</Password>
            </AdminUser>
```

Thanks,
Hari

**Comment by hari819** [comment]
Hello Team ,

could you please point me if i am missing some configuration for making both email and non-email usernames working in 5.11 version same as 5.10 ?

thanks,
Hari

**Comment by ayshsandu** [comment]
Hi @hari819,

> now is it mandatory to move to the new configuration model ? , it was all working in 5.9 and 5.10 version .

Please note that it is advised to use deployement.toml based configurations for the latest versions of WSO2IS as we have introduced it for simplified configuration management capabilities and **moving away from the fallback strategy to remove deployement.toml and use .XML based configurations.**

For your initial question, it seems along with the fixes in https://github.com/wso2/identity-apps/pull/618 and https://github.com/wso2/product-is/issues/8117, the support for allowing both email and non-email usernames has been removed.

**Comment by hari819** [comment]
> Hi @hari819,
> 
> > now is it mandatory to move to the new configuration model ? , it was all working in 5.9 and 5.10 version .
> 
> Please note that it is advised to use deployement.toml based configurations for the latest versions of WSO2IS as we have introduced it for simplified configuration management capabilities and **moving away from the fallback strategy to remove deployement.toml and use .XML based configurations.**
> 
> For your initial question, it seems along with the fixes in [wso2/identity-apps#618](https://github.com/wso2/identity-apps/pull/618) and #8117, the support for allowing both email and non-email usernames has been removed. I will further analyze and update this.

thankyou @ayshsandu , I will start moving the config towards deployment,toml , 
with `<EnableEmailUserName>true</EnableEmailUserName>` and the following regular expressions in user-mgmt.xml i could get admin/adminpassword work for the wso2is console and only the email-username work for my application ,non-email username which was working till 5.10 version is not working as you mentioned ,

![image](https://user-images.githubusercontent.com/12997071/102611448-ee89d200-4154-11eb-92bc-7209fe562146.png)
 

I will wait for further updates,

Thanks,
Hari

**Comment by hari819** [comment]
hello @ayshsandu  , would it be possible to check if there is a workaround in wso2-is-5.11 to get both username and email-username working with `<EnableEmailUserName>true</EnableEmailUserName>`,

thanks,

**Comment by sachiniWettasinghe** [comment]
This issue is fixed now. To get both username and email-username working with `<EnableEmailUserName>true</EnableEmailUserName>`, please add the following configuration in the deployment.toml file. 
```
[tenant_mgt]
enable_email_domain = true
disable_email_domain_validation = true
```

**Comment by hari819** [comment]
@sachiniWettasinghe ,
Many thanks for fixing this and replying to this thread , 

could you please let me know which version of wso2IS should I update to to use this functionality?.

**Comment by sachiniWettasinghe** [comment]
Hi @hari819,

This issue is fixed in WSO2 IS 5.11.0. Please add the configs given in [1] to apply this fix.

[1] https://github.com/wso2/product-is/issues/10760#issuecomment-873862021

**Comment by hari819** [comment]
thankyou @sachiniWettasinghe

**Comment by hari819** [comment]
@sachiniWettasinghe , could you please let me know what will be the location of these config , if i am using the old configuration style without deployment.toml,

where should i add the properties in carbon.xml?

**Comment by hari819** [comment]
@sachiniWettasinghe , i could get the property from here , 

![image](https://user-images.githubusercontent.com/12997071/124875755-e1480e00-dfe6-11eb-831b-4cf67ebdb489.png)

thanks ,

**Comment by hari819** [comment]
@sachiniWettasinghe @AnuradhaSK ,

i have downloaded a fresh copy of wso2is-511 from github , and added this extra the above configuration in carbon.xml ,

```
    <EnableEmailUserName>true</EnableEmailUserName>
    <!--https://github.com/wso2/product-is/issues/10760-->
    <!--https://github.com/wso2/carbon-identity-framework/pull/3582/files-->
    <DisableEmailUserNameValidation>true</DisableEmailUserNameValidation>
```

I am still getting the same error that UserName should always be an email ,
![image](https://user-images.githubusercontent.com/12997071/125414639-e9c24417-9217-4c5e-86d5-d6e6c4e087cf.png)

can you confirm this works in wso2is-511?

Thanks,

**Comment by hari819** [comment]
@sachiniWettasinghe , @AnuradhaSK ,

I could not see any of the changes present in the above merges present in wso2is-511 ,  example the new property not present in carbon.xml.j2 template ,

![image](https://user-images.githubusercontent.com/12997071/125456002-148c4150-24e6-425d-8061-611275908bb5.png)

any idea how it will work in the current release of wso2is 5.11.0?

Thanks,

**Comment by dishelt** [comment]
Hi!. any idea how it will work in the current release of wso2is 5.11.0?

**Comment by rksk** [comment]
> Hi!. any idea how it will work in the current release of wso2is 5.11.0?

This is fixed in 5.11.0 after the GA release as an update. You can obtain the updates, if you have a subscription.
